/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs1a.currencyconverter;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.json.JSONObject;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.net.URLConnection;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;


/**
 *
 * @author Cristobal PC
 */
public class Login extends javax.swing.JFrame {
    private boolean firstclick = true;

    /**
     * Creates new form Login
     */
    
    
    
    
    public Login() {
        initComponents();
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        homebtn = new javax.swing.JButton();
        logbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        convertbtn = new javax.swing.JButton();
        settingsbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pnlCards = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logintxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        submitbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        recoverbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        registerbtn = new javax.swing.JButton();
        Registration = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        register_nametxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        register_passwordtxt = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        register_retypetxt = new javax.swing.JPasswordField();
        register_submitbtn = new javax.swing.JButton();
        register_backbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Convert = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        convert_btn = new javax.swing.JButton();
        from_box = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        from_value = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        to_box = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        Log = new javax.swing.JPanel();
        show_button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Download = new javax.swing.JButton();
        Settings = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        welcometext = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(188, 156, 34));
        sidepane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sidepane.setForeground(new java.awt.Color(255, 255, 255));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebtn.setBackground(new java.awt.Color(188, 156, 34));
        homebtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setText("Home");
        homebtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        homebtn.setBorderPainted(false);
        homebtn.setContentAreaFilled(false);
        homebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        sidepane.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 60));

        logbtn.setBackground(new java.awt.Color(188, 156, 34));
        logbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        logbtn.setForeground(new java.awt.Color(255, 255, 255));
        logbtn.setText("Logs");
        logbtn.setBorder(null);
        logbtn.setBorderPainted(false);
        logbtn.setContentAreaFilled(false);
        logbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtnActionPerformed(evt);
            }
        });
        sidepane.add(logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 180, 60));

        exitbtn.setBackground(new java.awt.Color(188, 156, 34));
        exitbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setText("Exit");
        exitbtn.setBorder(null);
        exitbtn.setBorderPainted(false);
        exitbtn.setContentAreaFilled(false);
        exitbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
        });
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        sidepane.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 180, 40));

        convertbtn.setBackground(new java.awt.Color(188, 156, 34));
        convertbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        convertbtn.setForeground(new java.awt.Color(255, 255, 255));
        convertbtn.setText("Convert");
        convertbtn.setBorder(null);
        convertbtn.setBorderPainted(false);
        convertbtn.setContentAreaFilled(false);
        convertbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertbtnActionPerformed(evt);
            }
        });
        sidepane.add(convertbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 180, 60));

        settingsbtn.setBackground(new java.awt.Color(188, 156, 34));
        settingsbtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        settingsbtn.setForeground(new java.awt.Color(255, 255, 255));
        settingsbtn.setText("Settings");
        settingsbtn.setBorder(null);
        settingsbtn.setBorderPainted(false);
        settingsbtn.setContentAreaFilled(false);
        settingsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsbtnActionPerformed(evt);
            }
        });
        sidepane.add(settingsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 180, 60));

        getContentPane().add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 700));

        jPanel3.setBackground(new java.awt.Color(30, 30, 30));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCards.setBackground(new java.awt.Color(51, 51, 51));
        pnlCards.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlCards.setLayout(new java.awt.CardLayout());

        Login.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Cascadia Mono", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Cascadia Mono", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password:");

        logintxt.setBackground(new java.awt.Color(102, 102, 102));
        logintxt.setForeground(new java.awt.Color(255, 255, 255));
        logintxt.setText("Enter registered name.....");
        logintxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logintxtMouseClicked(evt);
            }
        });

        passwordtxt.setBackground(new java.awt.Color(102, 102, 102));
        passwordtxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordtxt.setText("jPasswordField1");
        passwordtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordtxtMouseClicked(evt);
            }
        });
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });

        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("Submit");
        submitbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitbtn.setContentAreaFilled(false);
        submitbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lost your account? ");

        recoverbtn.setForeground(new java.awt.Color(255, 255, 255));
        recoverbtn.setText("Recover here!");
        recoverbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        recoverbtn.setContentAreaFilled(false);
        recoverbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recoverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoverbtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Register, it's free!");

        registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        registerbtn.setText("Register today");
        registerbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerbtn.setContentAreaFilled(false);
        registerbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(150, 150, 150)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logintxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recoverbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addGap(66, 66, 66))))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addGap(0, 177, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recoverbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(104, 104, 104))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        pnlCards.add(Login, "card12");

        Registration.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name");

        register_nametxt.setBackground(new java.awt.Color(102, 102, 102));
        register_nametxt.setForeground(new java.awt.Color(255, 255, 255));
        register_nametxt.setText("Type your name here....");
        register_nametxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_nametxtMouseClicked(evt);
            }
        });
        register_nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_nametxtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");

        register_passwordtxt.setBackground(new java.awt.Color(102, 102, 102));
        register_passwordtxt.setForeground(new java.awt.Color(255, 255, 255));
        register_passwordtxt.setText("jPasswordField1");
        register_passwordtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_passwordtxtMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Re-Type Password");

        register_retypetxt.setBackground(new java.awt.Color(102, 102, 102));
        register_retypetxt.setForeground(new java.awt.Color(255, 255, 255));
        register_retypetxt.setText("jPasswordField2");
        register_retypetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_retypetxtMouseClicked(evt);
            }
        });

        register_submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        register_submitbtn.setText("Submit");
        register_submitbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register_submitbtn.setContentAreaFilled(false);
        register_submitbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_submitbtnActionPerformed(evt);
            }
        });

        register_backbtn.setForeground(new java.awt.Color(255, 255, 255));
        register_backbtn.setText("Back");
        register_backbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register_backbtn.setContentAreaFilled(false);
        register_backbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_backbtnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign up");

        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("\"We will solely utilize \nyour information to \nestablish your \naccount, without \nexceeding or \ndeviating \nfrom this prupose.\"");
        jTextArea1.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout RegistrationLayout = new javax.swing.GroupLayout(Registration);
        Registration.setLayout(RegistrationLayout);
        RegistrationLayout.setHorizontalGroup(
            RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationLayout.createSequentialGroup()
                        .addComponent(register_backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(register_passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(register_nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(register_retypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(register_submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))))
            .addGroup(RegistrationLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 459, Short.MAX_VALUE))
            .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RegistrationLayout.createSequentialGroup()
                    .addGap(425, 425, 425)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(426, Short.MAX_VALUE)))
        );
        RegistrationLayout.setVerticalGroup(
            RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(register_backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(24, 24, 24)
                        .addComponent(register_nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(register_passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(register_retypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(register_submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RegistrationLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnlCards.add(Registration, "card5");

        Convert.setBackground(new java.awt.Color(51, 51, 51));

        jPanel5.setBackground(new java.awt.Color(62, 62, 62));

        convert_btn.setBackground(new java.awt.Color(51, 51, 51));
        convert_btn.setForeground(new java.awt.Color(255, 255, 255));
        convert_btn.setText("Convert");
        convert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    convert_btnActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        from_box.setBackground(new java.awt.Color(51, 51, 51));
        from_box.setForeground(new java.awt.Color(255, 255, 255));
        from_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTC", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLF", "CLP", "CNH", "CNY", "COP", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GGP", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "IMP", "INR", "IQD", "IRR", "ISK", "JEP", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLL", "SOS", "SRD", "SSP", "STD", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "YER", "ZAR", "ZMW", "ZWL" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From:");

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );

        from_value.setBackground(new java.awt.Color(102, 102, 102));
        from_value.setForeground(new java.awt.Color(255, 255, 255));
        from_value.setText("Amount here...");
        from_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_valueActionPerformed(evt);
            }
        });
        from_value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                from_valueKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                from_valueKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(convert_btn))
                    .addComponent(jLabel3)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(from_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(from_value, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(from_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(from_box, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(convert_btn)
                .addGap(42, 42, 42))
        );

        jPanel7.setBackground(new java.awt.Color(62, 62, 62));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("To:");

        to_box.setBackground(new java.awt.Color(51, 51, 51));
        to_box.setForeground(new java.awt.Color(255, 255, 255));
        to_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTC", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLF", "CLP", "CNH", "CNY", "COP", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GGP", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "IMP", "INR", "IQD", "IRR", "ISK", "JEP", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLL", "SOS", "SRD", "SSP", "STD", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "YER", "ZAR", "ZMW", "ZWL" }));
        to_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_boxActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(to_box, 0, 249, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel12)
                .addGap(40, 40, 40)
                .addComponent(to_box, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ConvertLayout = new javax.swing.GroupLayout(Convert);
        Convert.setLayout(ConvertLayout);
        ConvertLayout.setHorizontalGroup(
            ConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConvertLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        ConvertLayout.setVerticalGroup(
            ConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConvertLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(ConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pnlCards.add(Convert, "card3");

        Log.setBackground(new java.awt.Color(51, 51, 51));

        show_button.setText("Show");
        show_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_buttonActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(51, 51, 51));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Date", "From Currency", "From Value", "To Value", "Result"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTable2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(jTable2);

        Download.setText("Export");
        Download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    DownloadActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout LogLayout = new javax.swing.GroupLayout(Log);
        Log.setLayout(LogLayout);
        LogLayout.setHorizontalGroup(
            LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(LogLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(show_button)
                .addGap(18, 18, 18)
                .addComponent(Download)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogLayout.setVerticalGroup(
            LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(show_button)
                    .addComponent(Download))
                .addGap(26, 26, 26))
        );

        pnlCards.add(Log, "card4");

        Settings.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Developed by Alcaide, Aya-ay, Cristobal, Dantes, Sustiguer");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Need Help?");

        javax.swing.GroupLayout SettingsLayout = new javax.swing.GroupLayout(Settings);
        Settings.setLayout(SettingsLayout);
        SettingsLayout.setHorizontalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(239, 239, 239))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SettingsLayout.setVerticalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(34, 34, 34))
        );

        pnlCards.add(Settings, "card6");

        Home.setBackground(new java.awt.Color(51, 51, 51));

        welcometext.setFont(new java.awt.Font("Cascadia Mono", 0, 36)); // NOI18N
        welcometext.setForeground(new java.awt.Color(255, 255, 255));
        welcometext.setText("Welcome, Name");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("You are now free to use all of the features that this program offers.");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(welcometext)
                        .addGap(121, 121, 121)))
                .addGap(160, 160, 160))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(welcometext)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        pnlCards.add(Home, "card12");

        jPanel3.add(pnlCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 860, 660));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 920, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    boolean LoggedIn = false;

    private void settingsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsbtnActionPerformed
        // TODO add your handling code here:
        pnlCards.removeAll();
        pnlCards.add(Settings);
        pnlCards.repaint();
        pnlCards.revalidate();
    }//GEN-LAST:event_settingsbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitbtnActionPerformed

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        //Closes application
        System.exit(0);
    }//GEN-LAST:event_exitbtnMouseClicked

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        if (LoggedIn == false)
        {
            pnlCards.removeAll();
            pnlCards.add(Login);
            pnlCards.repaint();
            pnlCards.revalidate(); 
        }
        
        else
        {
            pnlCards.removeAll();
            pnlCards.add(Home);
            pnlCards.repaint();
            pnlCards.revalidate();
        }
        
        
    }//GEN-LAST:event_homebtnActionPerformed

    private void convertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertbtnActionPerformed
        // TODO add your handling code here:
        
        if (LoggedIn == false)
        {
            JOptionPane.showMessageDialog(null, "You must logged in first!", "Error!", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else
        {
            pnlCards.removeAll();
            pnlCards.add(Convert);
            pnlCards.repaint();
            pnlCards.revalidate();
        }
    }//GEN-LAST:event_convertbtnActionPerformed

    private void logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtnActionPerformed
        // TODO add your handling code here:
        if (LoggedIn == false)
        {
            JOptionPane.showMessageDialog(null, "You must logged in first!", "Error!", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else
        {
            pnlCards.removeAll();
            pnlCards.add(Log);
            pnlCards.repaint();
            pnlCards.revalidate();   
        }
        
    }//GEN-LAST:event_logbtnActionPerformed

    private void recoverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoverbtnActionPerformed
        // TODO add your handling code here:
        try {
            URL url = new URL("https://forms.gle/zAEF8j5h7S37MsQR7");
            Desktop.getDesktop().browse(url.toURI());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, "Your default browser should open", "Recover account", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_recoverbtnActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        // TODO add your handling code here:
        pnlCards.removeAll();
        pnlCards.add(Registration);
        pnlCards.repaint();
        pnlCards.revalidate();
    }//GEN-LAST:event_registerbtnActionPerformed

    private void register_backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_backbtnActionPerformed
        // TODO add your handling code here:
        pnlCards.removeAll();
        pnlCards.add(Login);
        pnlCards.repaint();
        pnlCards.revalidate();
    }//GEN-LAST:event_register_backbtnActionPerformed

    private void register_nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_nametxtActionPerformed

    private void from_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_valueActionPerformed
        // TODO add your handling code here:
        if (firstclick)
        {
            firstclick = false;
            from_value.setText("");
        }
    }//GEN-LAST:event_from_valueActionPerformed

    private void register_submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_submitbtnActionPerformed
        // TODO add your handling code here:
        String name = register_nametxt.getText();
        String password = register_passwordtxt.getText();
        String confirm = register_retypetxt.getText();

        Connection conn = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        if (!Objects.equals(password, confirm))
        {
            JOptionPane.showMessageDialog(null, "Error: Your password does not match", "Error Message", JOptionPane.ERROR_MESSAGE);
            register_passwordtxt.setText("");
            register_retypetxt.setText("");
        }

        else
        {
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");

                // Establish a connection to the database
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/userinfo", "root", "");

                stmt = conn.prepareStatement("SELECT * FROM userdata WHERE username = ?");
                stmt.setString(1, name);
                rs = stmt.executeQuery();

                if (rs.next())
                {
                    //If may account
                    JOptionPane.showMessageDialog(this, "Account already exists");
                    stmt.close();
                }

                else
                {
                    // Prepare an SQL statement for insertion
                    stmt = conn.prepareStatement("INSERT INTO userdata (username, password) VALUES (?, ?)");

                    // Retrieve the values of the registration form's text fields and insert them into the SQL statement
                    stmt.setString(1, register_nametxt.getText());
                    stmt.setString(2, register_passwordtxt.getText());


                    // Execute the SQL statement
                    int rowsAffected = stmt.executeUpdate();

                    if (rowsAffected > 0) {
                        // Registration successful
                        System.out.println("Account for: " + name + " is successfully created");
                        JOptionPane.showMessageDialog(null, "Success: Your account has been made!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        // Registration failed
                        JOptionPane.showMessageDialog(this, "Registration failed.");
                    }

                    stmt.close();
                    conn.close();
                }


            }

            catch (SQLException ex) {
                // Handle database connection errors
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Database connection error.");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        register_passwordtxt.setText("password here");
        register_retypetxt.setText("re-type here");
    }//GEN-LAST:event_register_submitbtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:

        //Retrive the texts in the text fields
        String username = logintxt.getText();
        String password = passwordtxt.getText();

            Connection conn = null;
            PreparedStatement stmt = null;
            ResultSet rs = null;

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/userinfo", "root", "");
                stmt = conn.prepareStatement("SELECT * FROM userdata WHERE username = ? AND password = ?");
                stmt.setString(1, username);
                stmt.setString(2, password);
                rs = stmt.executeQuery();

                if (rs.next()) {
                    // redirect to home page
                    System.out.println("User: " + username + " successfully logged in.");
                    pnlCards.removeAll();
                    pnlCards.add(Home);
                    pnlCards.repaint();
                    pnlCards.revalidate();
                    welcometext.setText("Welcome, " + username);
                    LoggedIn = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username or password. Please try again", "Error", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
                try {
                    if (rs != null) {
                        rs.close();
                    }
                    if (stmt != null) {
                        stmt.close();
                    }
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
    }//GEN-LAST:event_submitbtnActionPerformed

    private void convert_btnActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_convert_btnActionPerformed
        // TODO add your handling code here:
        String text = from_value.getText();

        float from = Float.parseFloat(text);
        String from_currency = from_box.getSelectedItem().toString();


        String to_currency = to_box.getSelectedItem().toString();

        String url_str = "https://api.exchangerate.host/latest?base=" + from_currency;

        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder().url(url_str).get().build();

        Response response = client.newCall(request).execute();
        String stringResponse = response.body().string();
        JSONObject jsonObject = new JSONObject(stringResponse);
        JSONObject ratesObject = jsonObject.getJSONObject("rates");

        float rate = ratesObject.getFloat(to_currency);

        float result = Math.round(rate * from);

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            // Establish a connection to the database


            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transactions", "root", "");
            LocalDateTime now = LocalDateTime.now();
            // Prepare an SQL statement for insertion
            PreparedStatement stmt = conn.prepareStatement("INSERT INTO log (Name, Date, `From Currency`, `From Value`, `To Value`, `Result`) VALUES (?, ?, ?, ?, ?, ?)");

            // Retrieve the values of the registration form's text fields and insert them into the SQL statement
            stmt.setString(1, logintxt.getText());
            stmt.setString(2, String.valueOf(now));
            stmt.setString(3, from_currency);
            stmt.setString(4, String.valueOf(from));
            stmt.setString(5, to_currency);
            stmt.setString(6, String.valueOf(result));

            // Execute the SQL statement
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("Transaction of: " + logintxt.getText() + " is successfully created");
                JOptionPane.showMessageDialog(null, from_currency + from + " is " + to_currency + result, "Success!", JOptionPane.INFORMATION_MESSAGE);
            } else {

                JOptionPane.showMessageDialog(this, "Conversion failed.");
            }

            stmt.close();
            conn.close();
        }

        catch (SQLException ex) {
            // Handle database connection errors
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database connection error.");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_convert_btnActionPerformed

    private void from_valueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_from_valueKeyPressed
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        
        if (Character.isAlphabetic(key))
        {
            JOptionPane.showMessageDialog(null, "Only input numerical values!", "Error!", JOptionPane.INFORMATION_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_from_valueKeyPressed

    private void to_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_boxActionPerformed

    private void show_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_buttonActionPerformed
        // TODO add your handling code here:
        jTable2.setModel(new DefaultTableModel(null, new String[] {"Name", "Date", "From Currency", "From Value", "To Value", "Result"}));

        try {
                Class.forName("com.mysql.cj.jdbc.Driver");

                // Establish a connection to the database
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transactions", "root", "");

                Statement st = conn.createStatement();
                String user = logintxt.getText();
                String query = "SELECT * FROM log WHERE Name = '"+user+"'";
                ResultSet resultSet = st.executeQuery(query);
                ResultSetMetaData rsmd = resultSet.getMetaData();
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                
                String name, date, from_currency, from_value, to_currency, result;
                while (resultSet.next()){
                    name = resultSet.getString(1);
                    date = resultSet.getString(2);
                    from_currency = resultSet.getString(3);
                    from_value = resultSet.getString(4);
                    to_currency = resultSet.getString(5);
                    result = resultSet.getString(6);

                    String[] row = {name, date, from_currency, from_value, to_currency, result};
                    model.addRow(row);
                    
                }
                conn.close();
            }

            catch (SQLException ex) {
                // Handle database connection errors
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Database connection error.");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_show_buttonActionPerformed

    private void from_valueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_from_valueKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_from_valueKeyTyped

    public void logintxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logintxtMouseClicked
        // TODO add your handling code here:
        
        if (firstclick)
        {
            firstclick = false;
            logintxt.setText("");
        }


    }//GEN-LAST:event_logintxtMouseClicked

    public void passwordtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordtxtMouseClicked
        // TODO add your handling code here:
        if (firstclick)
        {
            firstclick = false;
            passwordtxt.setText("");
        }
    }//GEN-LAST:event_passwordtxtMouseClicked

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void register_nametxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_nametxtMouseClicked
        // TODO add your handling code here:
        if (firstclick)
        {
            firstclick = false;
            register_nametxt.setText("");
        }
    }//GEN-LAST:event_register_nametxtMouseClicked

    private void register_passwordtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_passwordtxtMouseClicked
        // TODO add your handling code here:
        if (firstclick)
        {
            firstclick = false;
            register_passwordtxt.setText("");
        }
    }//GEN-LAST:event_register_passwordtxtMouseClicked

    private void register_retypetxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_retypetxtMouseClicked
        // TODO add your handling code here:
        if (firstclick)
        {
            firstclick = false;
            register_retypetxt.setText("");
        }
    }//GEN-LAST:event_register_retypetxtMouseClicked

    private void DownloadActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_DownloadActionPerformed

        try {

            //Counts the rows and columns of the jTable
            int rowCount = jTable2.getRowCount();
            int colCount = jTable2.getColumnCount();

            // Create a new XSSFWorkbook object
            XSSFWorkbook workbook = new XSSFWorkbook();

            // Create a new sheet in the workbook
            XSSFSheet sheet = workbook.createSheet("Table Data");


            // Create a new Row and Cell for the headers
            Row headerRow = sheet.createRow(0);
            for (int i = 0; i < colCount; i++)
            {
                Cell headerCell = headerRow.createCell(i);
                headerCell.setCellValue(jTable2.getColumnName(i));
            }

            //Iterate over the rows and columns of the JTable, and add the data to the Excel sheet
            for (int i = 0; i < rowCount; i++) {
                Row row = sheet.createRow(i + 1);
                for (int j = 0; j < colCount; j++) {
                    Cell cell = row.createCell(j);
                    cell.setCellValue(jTable2.getValueAt(i, j).toString());
                }
            }

            //Prompts the user for directory
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Export Table");
            JFrame frame = new JFrame ("Export Data");
            int userSelection = fileChooser.showSaveDialog(frame);

            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                String filePath = fileToSave.getAbsolutePath() + ".xlsx";

                // Write the workbook to an Excel file
                FileOutputStream outputStream = new FileOutputStream(filePath);
                workbook.write(outputStream);
                workbook.close();

                //Success message
                JOptionPane.showMessageDialog(frame, "Data named: " + fileToSave.getName() + " is exported.");
                frame.dispose();
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }




    } //GEN-LAST:event_DownloadActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Convert;
    private javax.swing.JButton Download;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Log;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Registration;
    private javax.swing.JPanel Settings;
    private javax.swing.JButton convert_btn;
    private javax.swing.JButton convertbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JComboBox<String> from_box;
    private javax.swing.JTextField from_value;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton logbtn;
    private javax.swing.JTextField logintxt;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JButton recoverbtn;
    private javax.swing.JButton register_backbtn;
    private javax.swing.JTextField register_nametxt;
    private javax.swing.JPasswordField register_passwordtxt;
    private javax.swing.JPasswordField register_retypetxt;
    private javax.swing.JButton register_submitbtn;
    private javax.swing.JButton registerbtn;
    private javax.swing.JButton settingsbtn;
    private javax.swing.JButton show_button;
    private javax.swing.JPanel sidepane;
    private javax.swing.JButton submitbtn;
    private javax.swing.JComboBox<String> to_box;
    private javax.swing.JLabel welcometext;
    // End of variables declaration//GEN-END:variables
}
